name: Draft release

on:
  release:
    types:
      - created
      - edited
  push:

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      # - name: Cache Dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      # - name: Build Go Application
      #   run: go build -o myapp.go

      # - name: Set up AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: Log in to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and Push Docker Image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $ECR_REGISTRY/myapp:$IMAGE_TAG .
      #     docker push $ECR_REGISTRY/myapp:$IMAGE_TAG

      - name: Create Tag
        run: |
          TAG_NAME=$(date +'%Y%m%d-%H%M%S')
          echo "$TAG_NAME"
          # git tag $TAG_NAME
          # git push origin $TAG_NAME
